### ISSUE TITLE
Error could not find region configuration

### ISSUE THREAD

**Issue by jcpsantiago** [tzzh/pod-tzzh-aws#3]
```clojure
user=> (s3/list-buckets)
clojure.lang.ExceptionInfo: MissingRegion: could not find region configuration [at <repl>:4:1]
```

where/how must the region be defined? I am using `~/.aws/credentials` with a list of profiles which already define that information, works with aws cli. Will it also work with this pod?

**Comment by borkdude** [comment]
@jcpsantiago By setting `export AWS_REGION="eu-west-1"` it worked for me.

**Comment by jcpsantiago** [comment]
yap that works, but I'm still no lucky

```clojure
user=> (s3/list-buckets)
clojure.lang.ExceptionInfo: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors [at <repl>:4:1]
```

We use Okta and it's always a headache 😩 I'll try to figure this out. Region problem solved anyways.

**Comment by borkdude** [comment]
@jcpsantiago I'm not the author of this pod. Maybe @tzzh has better ideas!

**Comment by borkdude** [comment]
@jcpsantiago I found an issue that mentions your second error message here: https://github.com/aws/aws-sdk-go/issues/2914
