### ISSUE TITLE
Code generation for other services

### ISSUE THREAD

**Issue by zackteo** [tzzh/pod-tzzh-aws#4]
Was thinking of using this for EC2 but I don't quite understand how to generate the code to do so. 

Perhaps it would be good to explain in the README how one might do so if the service they like to use isn't included currently?

**Comment by tzzh** [comment]
Hey, so I've just updated the code generation a bit, if you change https://github.com/tzzh/pod-tzzh-aws/blob/6633df0b2f5080f7d4374b5d4f20331d556f1c2f/gen/generate.clj#L11-L21 to what you need and then run `make generate` then that should generate the go code you need (and then run `go build` to build the binary).
Let me know if that works.
